config/routes.rb
CourseWatcher::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :courses, only: [:show]
  resources :course_selections, only: [:new, :create, :destroy, :show]
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  before_create :create_remember_token

  # Database associations
  has_many :course_selections
  has_many :courses, through: :course_selections, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+\.[a-z]+\z/i

  has_secure_password

  validates :name, presence: true, length: { maximum: 35 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }

  # Presence validations for password and its confirmation automatically
  # added by has_secure_password
  validates :password, length: { minimum: 6, maximum: 25 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  # Course selection methods

  def watch(course_subject, course_number, course_section=nil)
    if course_section
      course_set = Course.where(subject: course_subject, 
                                number: course_number,
                                section: course_section)
      self.course_selections.create(course_id: course_set.first.id)
      return course_set
    else
      # Check if any courses with given subj and number are in database
      course_set = Course.where(subject: course_subject, number: course_number)

      if course_set.empty?
        # No matching courses in database, so validate and initialize all 
        # sections of this course
        course_set = Course.validate_and_init(course_subject, course_number)

        if course_set
          # Validation successful. Create the course selection of there is one section
          # and return the set of courses (all sections)
          if course_set.count == 1
            course_built = course_set.first
            course_in_db = Course.find_by(subject: course_built.subject,
                                          number: course_built.number,
                                          section: course_built.section)
            self.course_selections.create(course_id: course_in_db.id)
          end
          return course_set
        else
          # Validation not successful. Return a course object with an error
          course_set = Array.new
          course = Course.create(subject: course_subject, number: course_number)
          if course.errors.empty?
            course.errors.add(:base, "#{course_subject} #{course_number} 
                            isn't a valid course this term.")
            Course.find_by(subject: course_subject, number: course_number).destroy
          end
          course_set.push(course)
        end
      else
        if course_set.count > 1
          # Multiple sections. Return the set of all of them
          return course_set
        else
          # Only one section. Create the course selection and return the course set
          course = course_set.first
          self.course_selections.create(course_id: course.id)
          return course_set
        end
      end
    end
  end

  def unwatch!(other_course)
    self.course_selections.find_by(course_id: other_course.id).destroy
  end

  def watching?(other_course)
    self.course_selections.find_by(course_id: other_course.id)
  end

  # # Return false if course doesn't exist in db, return set of courses if there 
  # # are multiple sections of this course, return a set of courses containing 
  # # one course (the course) if user is following it (only one section of it), or
  # # return nil if the user isn't following the course (that has only one section)
  # def watching_course?(course_subject, course_number)
  #   course_set = Course.where(subject: course_subject, number: course_number)
  #   if course_set.empty?
  #     return false
  #   else
  #     if course_set.count > 1
  #       return course_set
  #     else
  #       if self.watching?(course_set.first)
  #         return course_set
  #       else
  #         return false
  #     end
  #   end
  # end

  # Above was the proposed return types, but ruby was not doing what I expected.
  # 
  # Return false for a course not in db, nil if course is in db but user isn't
  # following it, a CourseSelection if course is in db and user is following it,
  # and an ActiveRecord::Relation (set of courses) if there are multiple sections
  # of the course
  def watching_course?(course_subject, course_number, course_section)
    if course_section
      course = Course.find_by(subject: course_subject, 
                              number: course_number,
                              section: course_section)
      self.watching?(course)
    else
      course_set = Course.where(subject: course_subject, number: course_number)

      unless course_set.empty?
        self.watching?(course_set.first) unless course_set.count > 1
      end
    end
  end


  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome to CourseWatch!'
      sign_in @user
      # redirect_to user_path(@user)
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @current_page = 'profile'
    @user = User.find(params[:id])
    @courses = @user.courses
  end

  def edit
 
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy

  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters
    def signed_in_user
      unless signed_in?
        flash[:warning] = "Not authorized! Please sign in."
        redirect_to signin_path
      end
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        flash[:warning] = "You're not allowed to view that page!"
        redirect_to root_url
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>

<div class="container" id="container-login">
  <h1>Edit Your Account</h1>
  <div class="login-form general-form">
    <%= form_for(@user) do |f| %>
      <legend>Update Profile</legend>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.text_field :email, id: "inputEmail", class: "form-control login-field", placeholder: "New Email" %>
        <label class="login-field-icon fui-mail" for="inputEmail"></label>
      </div>
      
      <div class="form-group">
        <%= f.password_field :password, id: "inputPassword", 
        class: "form-control login-field", placeholder: "New Password" %>
        <label class="login-field-icon fui-lock" for="inputPassword"></label>
      </div>
      
      <div class="form-group">
        <%= f.password_field :password_confirmation, id: "inputConfirmation", class: "form-control login-field", placeholder: "Confirmation" %>
        <label class="login-field-icon fui-lock" for="inputConfirmation"></label>
      </div>
      <%= f.submit "Save changes", class: "btn btn-primary btn-lg" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<div class="container" id="container-login">
  <h1>Create a free acount</h1>
  <div class="login-form general-form">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">  
        <%= f.text_field :name, id: "inputName", class: "form-control login-field",
        placeholder: "Name"%>
        <label class="login-field-icon fui-user" for="inputName"></label>
      </div>
    
      <div class="form-group">
        <%= f.text_field :email, id: "inputEmail", class: "form-control login-field",
        placeholder: "Email" %>
        <label class="login-field-icon fui-mail" for="inputEmail"></label>
      </div>

      <div class="form-group">
        <%= f.password_field :password, id: "inputPassword", class: "form-control login-field",
        placeholder: "Password" %>
        <label class="login-field-icon fui-lock" for="inputPassword"></label>
      </div> 
    
      <div class="form-group">
        <%= f.password_field :password_confirmation, id: "inputConfirmation", 
        class: "form-control login-field", placeholder: "Confirm Password" %>
        <label class="login-field-icon fui-lock" for="inputConfirmation"></label>
      </div>

      <%= f.submit "Submit", class: "btn btn-primary"%>
    <% end %>
  </div>
  <p>Already a member? <%= link_to "Sign in", signin_path %>.</p>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="tables">Course Watchlist</h1>
    </div>
  </div>

  <% if @courses.empty? %>
    <p>Looks like you haven't added any courses yet. Get started!</p>
  <% else %>
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Course</th>
          <th>Section</th>
          <th>Availability</th>
          <th>Instructor</th>
          <th>Period</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @courses.each do |course| %>
          <tr class="info">
            <td><%= course.subject %> <%= course.number %></td>
            <td><%= course.section %></td>
            <% if course.available? %>
              <td class="text-success" id="availability">Available</td>
            <% else %>
              <td class="text-danger" id="availability">Not available</td>
            <% end %>
            <td><%= course.instructor %></td>
            <td><%= course.period %></td>
            <td><a href="<%= course_selection_path(course.id) %>">More info</a></td>
          </tr>    
        <% end %>
      </tbody>
    </table>
  <% end %>

  <%= link_to "Add a course", new_course_selection_path, class: "btn btn-default" %>

</div>