config/routes.rb
CourseWatcher::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :courses, only: [:show]
  resources :course_selections, only: [:new, :create, :destroy, :show]
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/course_selection.rb
class CourseSelection < ActiveRecord::Base
  belongs_to :user
  belongs_to :course

  validates :user, presence: true
  validates :course, presence: true

  def init_notification_attributes
    if self.course.available?
      self.update_attributes(user_needs_notified: false,
                             course_initially_available: true)
    end
  end

  # Email necessary users if their course is available
  def self.notify_users
    CourseSelection.all.each do |course_selection|
      if course_selection.course.available?
        # Email the user if needed
        if course_selection.user_needs_notified
          UserMailer.course_notification_email(course_selection.user,
                                               course_selection.course).deliver
          course_selection.update_attribute(:user_needs_notified, false)
          puts "Emailed #{course_selection.user.name} about 
          #{course_selection.course.subject} #{course_selection.course.number}"
        end
      else
        if course_selection.course_initially_available
          course_selection.update_attribute(:user_needs_notified, true)
        end
      end
    end
  end

end

app/controllers/course_selections_controller.rb
class CourseSelectionsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_course_selection, only: [:show]
  # TODO check for deleting course selections

  def new
    @course = Course.new
  end

  def show
    @title = "#{@course.subject} #{@course.number}"
  end

  def create
    @input_subject = params[:course_subject].strip.upcase
    @input_number = params[:course_number].to_i
    @input_section = params[:course_section]

    # Make the user watch the course if not already watching it
    if current_user.watching_course?(@input_subject, @input_number, 
                                     @input_section)
      flash[:danger] = "You're already watching #{@input_subject} #{@input_number}."
      redirect_to new_course_selection_path
    else
      @course_set = current_user.watch(@input_subject, @input_number, 
                                       @input_section)
      @course = @course_set.first

      # The course has several sections and/or labs. User needs to specify 
      # which one to watch
      if @course_set.count > 1
        render 'new'

      # One course section. Course selection has been made or course wasn't valid
      else
        if @course.errors.empty?
          # Potential Ajax implementation here!
          flash[:success] = "#{@course_set.first.subject} #{@course_set.first.number} 
          section #{@course_set.first.section} added."

          # Initialize notification attributes of the course selection
          CourseSelection.find_by(user_id: current_user.id, 
                                  course_id: @course.id).init_notification_attributes

          redirect_to user_path(current_user)
        else
          render 'new'
        end
      end
    end

  end

  def destroy
    course = CourseSelection.find(params[:id]).course
    current_user.unwatch!(course)
    flash[:warning] = "#{course.subject} #{course.number} section #{course.section} 
    removed from your watchlist."
    redirect_to user_path(current_user)
  end

  private

    # Before filters
    def signed_in_user
      unless signed_in?
        flash[:warning] = "Not authorized! Please sign in."
        redirect_to signin_path
      end
    end

    def correct_course_selection
      @user = current_user
      @course = Course.find(params[:id])
      @course_selection = CourseSelection.find_by(user_id: @user.id, 
                                                  course_id: @course.id)
      if @course_selection.nil?
        flash[:warning] = "Not authorized to view that page!"
        redirect_to @user
      end
    end

end

app/helpers/course_selections_helper.rb
module CourseSelectionsHelper

    
end

app/views/course_selections/_course_selection_form.html.erb
<div class="login-form general-form">
  <%= form_tag course_selections_path do %>
    <%= render 'shared/error_messages', object: @course %>
    
    <div class="form-group">
      <%= text_field_tag :course_subject, params[:course_subject], 
      id: "inputSubject", class: "form-control login-field", placeholder: "Course (e.g. COSC)" %>
      <label class="login-field-icon fui-book" for="inputName"></label>
    </div>

    <div class="form-group">
      <%= text_field_tag :course_number, params[:course_number], 
      id: "inputNumber", class: "form-control login-field", placeholder: "Course Number (e.g. 50)" %>
      <label class="login-field-icon fui-search" for="inputNumber"></label>
    </div>

    <%= submit_tag "Add course", class: "btn btn-success" %>
  <% end %>
</div>

app/views/course_selections/_sections_table.html.erb
<div class="col-lg-12">
  <div class="page-header">
    <h1 id="tables">Sections / Labs</h1>
  </div>
</div>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Course</th>
      <th>Section</th>
      <th>Availability</th>
      <th>Instructor</th>
      <th>Period</th>
      <th>Limit</th>
      <th>Enrollment</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @course_set.each do |course| %>
      <tr class="info">
        <td><%= course.subject %> <%= course.number %></td>
        <td><%= course.section %></td>
        <% if course.available? %>
          <td class="text-success" id="availability">Available</td>
        <% else %>
          <td class="text-danger" id="availability">Not available</td>
        <% end %>
        <td><%= course.instructor %></td>
        <td><%= course.period %></td>
        <td><%= course.limit %></td>
        <td><%= course.enrollment %></td>
        <td>
          <%= form_tag course_selections_path do %>
            <div>
              <%= hidden_field_tag 'course_subject', @input_subject %>
              <%= hidden_field_tag 'course_number', @input_number %>
              <%= hidden_field_tag 'course_section', course.section %>
            </div>
            <%= submit_tag "Select", class: "btn btn-primary btn-xs" %>
          <% end %>
        </td>
      </tr>    
    <% end %>
  </tbody>
</table>

app/views/course_selections/new.html.erb
<% provide(:title, "New Course") %>

<div class="container">

  <h1>Start watching courses</h1>

  <%= render 'course_selection_form' %>

  <% if @course_set && @course_set.count > 1 %>

    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">Selection Alert</h3>
      </div>
      <div class="panel-body">
        The course you selected has multiple sections and/or labs. Please specify
        which one you'd like to watch.
      </div>
    </div>
    
    <%= render 'sections_table' %>

  <% end %>

  <ul class="pager">
    <li><%= link_to "Back to profile", user_path(current_user) %></li>
  </ul>

</div>

app/views/course_selections/show.html.erb
<% provide(:title, @title) %>

<div class="container">

  <h2><%= @course.subject %> <%= @course.number %></h2>
  <h4>Section: <%= @course.section %></h4>
  <ul class="list-group center" id="course-show">
    <li class="list-group-item active">
      <%= @course.title %>
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.period) %></span>
      Period
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.instructor) %></span>
      Instructor
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.limit) %></span>
      Limit
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.enrollment) %></span>
      Enrolled
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.status) %></span>
      Status
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.cross_list) %></span>
      Xlist
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.room) %></span>
      Room
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.building) %></span>
      Building
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.distrib) %></span>
      Distrib
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.world_culture) %></span>
      World Culture
    </li>

    <li class="list-group-item">
      <span class="badge"><%= print_attribute(@course.crn) %></span>
      CRN
    </li>

  </ul>


  <%= form_for @course_selection, html: { method: :delete } do |f| %>
    <%= f.submit "Unwatch Course", class: "btn btn-danger" %>
  <% end %>

</div>