config/routes.rb
CourseWatcher::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :courses, only: [:show]
  resources :course_selections, only: [:new, :create, :destroy, :show]
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer class="footer-2 bg-midnight-blue">
  <div class="container">
    <nav class="pull-left">
      <div class="additional-links">
        <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a>
      </div>
    </nav>
    <div class="social-btns pull-right">
      <a href="mailto:coursewatchdartmouth@gmail.com"><div class="fui-mail"></div><div class="fui-mail"></div></a>
    </div>
    
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header-11">
  <div class="container">
    <div class="row">
      <div class="navbar col-sm-12" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle"></button>
          <%= link_to("CourseWatch", root_path, class: 'brand') %>
        </div>
        <div class="collapse navbar-collapse pull-right">
          <!-- Nav header elements / links to pages -->
          <ul class="nav pull-left">
            <li class=<%= "active" if @current_page.eql? "home" %>>
              <%= link_to "HOME", root_path %>
            </li>
            <li class=<%= "active" if @current_page.eql? "about" %>>
              <%= link_to "ABOUT", about_path %>
            </li>
            <li class=<%= "active" if @current_page.eql? "contact" %>>
              <%= link_to "CONTACT", contact_path %>
            </li>
          
            <% unless @current_page.eql?  "signin" %>

              <% unless signed_in? %>
                <form class="navbar-form pull-left">
                  <%= link_to "SIGN IN", signin_path, class: "btn btn-primary" %>
                </form>
              <% else %>
                <form class="navbar-form pull-left">
                  <li class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">PROFILE<span class="caret"></span></button>
                    <span class="dropdown-arrow dropdown-arrow-inverse"></span>
                    <ul class="dropdown-menu dropdown-inverse">
                      <li><%= link_to "Watchlist", user_path(current_user) %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li><%= link_to "Sign Out", signout_path, method: :delete %></li>
                    </u>
                  </li>
                </form>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />

  <%= render 'layouts/shim' %>
</head>

<body>
  <div class="page-wrapper">
    <%= render 'layouts/header' %>
    
    <% flash.each do |key, value| %>
      <div class="alert alert-dismissable alert-<%= key %>">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <%= value %>
      </div>
    <% end %>

    <%= yield %>
  
    <%= render 'layouts/footer' %>
  </div>
</body>
  
  <%= debug(params) if Rails.env.development? %>

</html>